### ISSUE TITLE
capture the peak curve along with the snapshot

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/qvibe-analyser#32]

**Comment by JanSam** [comment]
Any progress with this one? As i understand, the snapshot saves a avg-avg curve? i would like to save the peak curve.

Nalleh

**Comment by 3ll3d00d** [comment]
Yes, it turned into quite a big change as I realised live isn't really live so much as a fast ticking average. I think this explains some of your preferences for how to capture. Changing this is a bit of an invasive job so takes a while.

**Comment by JanSam** [comment]
Ok, sorry to hear that :( Wasn’t my intention to give you a lot of extra work. But capturing and saving the peak curve would make it possible to save content clips/sweeps and compare them when doing adjustments like time aligning etc. Only way to do it (near)proper now, is to do screen shots, but that doesn’t make it easy comparing two curves.

IMO the live view is a bit hard to use for anything(unless i am missing something), because it is too rapid moving, and for my use, the peak and/or avg with some hold time will make a steady, repeatable curve you can use for something, be it for measuring content(like with VS) or for tweaking(like RTA in REW).

Nalleh

**Comment by 3ll3d00d** [comment]
Yes I agree (about the utility of the live view) however the live view being wrong means the average is also averaging more than it really should based in the configured parameters so it needs to be made correct

**Comment by JanSam** [comment]
Makes sense, and i agree. Let’s hope you can figure it out :)

**Comment by 3ll3d00d** [comment]
should be in the next build albeit will publish as a beta til some other bits are polished some more

**Comment by JanSam** [comment]
Downloaded and tested. Snapshot now captures the peak (and avg) correctly :) Awsome, thanks ;)
