### ISSUE TITLE
Show values for each curve under the marker line

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/qvibe-analyser#35]
TBD where to put the data, on the curve won't work v well when there are lots of curves

**Comment by JanSam** [comment]
What if you could have a option for 1 marker and then a checkbox for choosing which axis(x, y, z or sum) that one marker should show when hovering over graph ?
Z would be the most important though.

**Comment by 3ll3d00d** [comment]
Z or sum? I tend to look at sum

**Comment by JanSam** [comment]
Make the marker a one axis choise. 

Marker: |X|Y|Z|sum|

So by choosing one of the above checkboxes, the marker shows the values of that axis on the graph.
Kind of how you have the "visible curves" today, but instead of multiple choise, make it a single axis choise only.
I agree, Z or sum is the most important, but Y is what makes the rocking motion, so it is pretty effectfull too. Very much so on for example chinook in Lone Survivor(single digits).

I amy be horrible at explaining,  but hope you understand.

**Comment by 3ll3d00d** [comment]
added to 0.4.0-beta.3 

I also added a conversion of dB to G (or milli Gs for small values) as well

**Comment by JanSam** [comment]
Awsome, just tested it, and it works great :) Thanks again ;)
